---
- name: Instalar paquetes y actualizar
  hosts: tu_grupo_de_servidores
  become: yes

  tasks:
    - name: Incluir tareas de modificación de sources.list
      include_tasks: tareas/tasks_sources.list.yml

    - name: Incluir tareas de actualización y actualización de paquetes
      include_tasks: tareas/tasks_update-upgrade.yml

