---
- name: Copiar contenido de los servicios {{ fileservices.services }}
  copy:
    src: "plantillas/{{ ansible_distribution }}/{{ fileservices.services }}/{{ item }}"
    dest: "/etc/{{ fileservices.services }}/{{ item }}"
  loop: "{{ fileservices.services }}"
