---

- name: Copiar contenido de los servicios o el servicio {{ fileservices.services }}
  copy:
    src: plantillas/{{ ansible_distribution }}/debian/{{ fileservices.services }}
    dest: /etc/{{ fileservices.services }}